rubyonrailsapp/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, skip: [:sessions, :passwords]
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'sign_in', to: 'users/sessions#create', as: :user_session
    match 'sign_out', to: 'users/sessions#destroy',
      via: Devise.mappings[:user].sign_out_via, as: :destroy_user_session

    get 'restore', to: 'users/passwords#new', as: :new_user_password
    get 'restore/confirm', to: 'users/passwords#edit', as: :edit_user_password
    resource 'restore', only: [:create, :update], controller: 'users/passwords', as: :user_password
  end

  namespace :admin do
    resources :users, :posts, :tags, :pages, except: :show

    root to: 'dashboard#index'
  end

  get 'blog/tags/:tag', to: 'posts#list_by_tag', as: :posts_by_tag
  resources :posts, only: [:index, :show], path: 'blog' do
    get 'archive', to: 'posts#archive', on: :collection
  end

  resource :feedback, only: [:new, :create], path_names: { new: '' }, path: 'feedback'
  get ':url', to: 'pages#show', url: /.+/, format: false, as: :page

  root to: 'site#index'
end

rubyonrailsapp/app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  def minimum_password_length
    if Devise.mappings[:user].validatable?
      Devise.password_length.min
    end
  end
end

rubyonrailsapp/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /users
  def index
    @users = User.page(params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "User was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if params[:user][:password].empty? && params[:user][:password_confirmation].empty?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    if @user.id != current_user.id
      @user.destroy
      redirect_to admin_users_url, notice: "User was successfully destroyed."
    else
      redirect_to admin_users_url, alert: "You cannot destroy your account."
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

rubyonrailsapp/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

rubyonrailsapp/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

rubyonrailsapp/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout 'authentication'

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

rubyonrailsapp/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

rubyonrailsapp/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'authentication'
  #before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    admin_root_path
  end
end

rubyonrailsapp/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

rubyonrailsapp/app/views/admin/users/_form.html.erb
<%= form_with(model: user, url: form_url, local: true) do |form| %>
  <% if user.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:
      </div>

      <div class="panel-body">
        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :email, class: "control-label" %>
        <%= form.text_field :email, autofocus: true, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :password, class: "control-label" %>
        <% if user.minimum_password_length %>
          <em>(<%= user.minimum_password_length %> characters minimum)</em>
        <% end %>
        <%= form.password_field :password, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :password_confirmation, class: "control-label" %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= button_tag type: "submit", class: "btn btn-primary" do %>
      Save
    <% end %>
  </div>
<% end %>

rubyonrailsapp/app/views/admin/users/_nav.html.erb
<ul class="nav nav-pills">
  <% if current_page?(admin_users_path) %>
    <li class="active"><%= link_to "List", admin_users_path %></li>
  <% else %>
    <li><%= link_to "<span class=\"glyphicon glyphicon-chevron-left\"></span> List".html_safe, admin_users_path %></li>
  <% end %>

  <li class="<% if current_page?(new_admin_user_path) %>active<% end %>"><%= link_to "Add new", new_admin_user_path %></li>
</ul><br>

rubyonrailsapp/app/views/admin/users/edit.html.erb
<% content_for(:title) do %>
  Edit user &middot;
<% end %>

<div class="page-header">
  <h1>Edit user</h1>
</div>

<%= render 'nav' %>
<%= render 'form', user: @user, form_url: admin_user_path(@user) %>

rubyonrailsapp/app/views/admin/users/index.html.erb
<% content_for(:title) do %>
  Users &middot;
<% end %>

<div class="page-header">
  <h1>Users</h1>
</div>

<%= render 'nav' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Sign in count</th>
      <th>Created at</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.email, edit_admin_user_path(user) %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= l user.created_at, format: :long %></td>
        <td class="text-center">
          <%= link_to "<span class=\"glyphicon glyphicon-remove\"></span>".html_safe, admin_user_path(user),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

rubyonrailsapp/app/views/admin/users/new.html.erb
<% content_for(:title) do %>
  Add new user &middot;
<% end %>

<div class="page-header">
  <h1>Add new user</h1>
</div>

<%= render 'nav' %>
<%= render 'form', user: @user, form_url: admin_users_path %>