rubyonrailsapp/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, skip: [:sessions, :passwords]
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'sign_in', to: 'users/sessions#create', as: :user_session
    match 'sign_out', to: 'users/sessions#destroy',
      via: Devise.mappings[:user].sign_out_via, as: :destroy_user_session

    get 'restore', to: 'users/passwords#new', as: :new_user_password
    get 'restore/confirm', to: 'users/passwords#edit', as: :edit_user_password
    resource 'restore', only: [:create, :update], controller: 'users/passwords', as: :user_password
  end

  namespace :admin do
    resources :users, :posts, :tags, :pages, except: :show

    root to: 'dashboard#index'
  end

  get 'blog/tags/:tag', to: 'posts#list_by_tag', as: :posts_by_tag
  resources :posts, only: [:index, :show], path: 'blog' do
    get 'archive', to: 'posts#archive', on: :collection
  end

  resource :feedback, only: [:new, :create], path_names: { new: '' }, path: 'feedback'
  get ':url', to: 'pages#show', url: /.+/, format: false, as: :page

  root to: 'site#index'
end

rubyonrailsapp/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:title) %>Administration</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag "/public/apple-touch-icon-precomposed.png", :rel => "apple-touch-icon-precomposed", :type => "image/png" %><!-- 57×57px -->
    <%= favicon_link_tag "/public/favicon.ico", :rel => "shortcut icon" %><!-- 32×32px -->
    <%= stylesheet_link_tag "admin", :media => "all" %>
    <%= javascript_include_tag "admin" %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= admin_root_path %>">Rails Blog Sample</a>
        </div>

        <div id="navbar-main-collapse" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "<span class=\"glyphicon glyphicon-home\"></span> Open site".html_safe,
              root_path, target: "_blank" %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "<span class=\"glyphicon glyphicon-log-out\"></span> Sign out".html_safe,
              destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="well sidebar-nav">
            <h3>Navigation</h3>

            <ul>
              <li><%= link_to "Dashboard", admin_root_path %></li>
              <li>
                Blog
                <ul>
                  <li><%= link_to "Posts", admin_posts_path %></li>
                  <li><%= link_to "Tags", admin_tags_path %></li>
                </ul>
              </li>
              <li><%= link_to "Pages", admin_pages_path %></li>
              <li><%= link_to "Users", admin_users_path %></li>
            </ul>
          </div>
        </div>

        <div class="col-md-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
        <p>&copy; Rails Blog Sample, <%= Time.current.year %></p>
      </footer>
    </div>
  </body>
</html>

rubyonrailsapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:title) %>Rails Blog Sample</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag "/public/apple-touch-icon-precomposed.png", :rel => "apple-touch-icon-precomposed", :type => "image/png" %><!-- 57×57px -->
    <%= favicon_link_tag "/public/favicon.ico", :rel => "shortcut icon" %><!-- 32×32px -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">Rails Blog Sample</a>
        </div>

        <div id="navbar-main-collapse" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Blog", posts_path %></li>
            <li><%= link_to "About", page_path("about") %></li>
            <li><%= link_to "Feedback", feedback_path %></li>
          </ul>
        </div>
      </div>
    </nav>

    <% if content_for?(:breadcrumbs) %>
      <ul class="breadcrumb container">
        <li><%= link_to "Home", root_path %></li>
        <%= yield(:breadcrumbs) %>
      </ul>
    <% end %>

    <div class="container">
      <% if content_for?(:main_columns) %>
        <%= yield(:main_columns) %>
      <% else %>
        <div class="row">
          <div class="col-md-12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div>
      <% end %>

      <footer>
        <ul class="list-inline">
          <li class="pull-right">&copy; Rails Blog Sample, <%= Time.current.year %></li>

          <li><%= link_to "Blog", posts_path %></li>
          <li><%= link_to "About", page_path("about") %></li>
          <li><%= link_to "Feedback", feedback_path %></li>
        </ul>
      </footer>
    </div>
  </body>
</html>

rubyonrailsapp/app/views/layouts/application_blog.html.erb
<% content_for(:title) do %>
  Blog &middot;
<% end %>

<% content_for(:main_columns) do %>
  <div class="row">
   <div class="col-md-9">
     <div class="blog">
       <%= yield %>
     </div>
   </div>

   <div class="col-md-3">
     <div class="portlet">
       <h3>Browse</h3>

       <ul>
         <li><%= link_to "Archive", archive_posts_path %></li>
       <ul>
     </div>

     <% if !post_tags.empty? %>
       <div class="portlet">
         <h3>Tags</h3>

         <ul>
           <% post_tags.each do |post_tag| %>
            <li><%= link_to post_tag.name, posts_by_tag_path(post_tag) %></a></li>
          <% end %>
         <ul>
       </div>
     <% end %>
   </div>
 </div>
<% end %>

<%= render template: 'layouts/application' %>

rubyonrailsapp/app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:title) %>Rails Blog Sample</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag "/public/apple-touch-icon-precomposed.png", :rel => "apple-touch-icon-precomposed", :type => "image/png" %><!-- 57×57px -->
    <%= favicon_link_tag "/public/favicon.ico", :rel => "shortcut icon" %><!-- 32×32px -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container authentication">
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>