rubyonrailsapp/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, skip: [:sessions, :passwords]
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'sign_in', to: 'users/sessions#create', as: :user_session
    match 'sign_out', to: 'users/sessions#destroy',
      via: Devise.mappings[:user].sign_out_via, as: :destroy_user_session

    get 'restore', to: 'users/passwords#new', as: :new_user_password
    get 'restore/confirm', to: 'users/passwords#edit', as: :edit_user_password
    resource 'restore', only: [:create, :update], controller: 'users/passwords', as: :user_password
  end

  namespace :admin do
    resources :users, :posts, :tags, :pages, except: :show

    root to: 'dashboard#index'
  end

  get 'blog/tags/:tag', to: 'posts#list_by_tag', as: :posts_by_tag
  resources :posts, only: [:index, :show], path: 'blog' do
    get 'archive', to: 'posts#archive', on: :collection
  end

  resource :feedback, only: [:new, :create], path_names: { new: '' }, path: 'feedback'
  get ':url', to: 'pages#show', url: /.+/, format: false, as: :page

  root to: 'site#index'
end

rubyonrailsapp/app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId

  STATUS_DRAFT = 1
  STATUS_PUBLISHED = 2
  STATUS_ARCHIVED = 3

  attr_accessor :new_tag_ids

  belongs_to :user
  has_many :post_tags
  has_many :tags, through: :post_tags
  before_save :set_published_date
  after_save :update_tags

  validates :title, :body, :snippet, :status, presence: true
  validates :title, length: { maximum: 150 }
  validates :status, inclusion: { in: [STATUS_DRAFT, STATUS_PUBLISHED, STATUS_ARCHIVED] }

  default_scope { order(created_at: :desc) }
  scope :active, -> { where(status: [STATUS_PUBLISHED, STATUS_ARCHIVED]) }
  scope :published, -> { where(status: STATUS_PUBLISHED) }
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    !slug || title_changed?
  end

  def set_published_date
    if !self.published_date && [STATUS_PUBLISHED, STATUS_ARCHIVED].include?(status)
      self.published_date = Time.now
    end
  end

  def update_tags
    new_tag_ids = self.new_tag_ids.reject(&:empty?).map(&:to_i)
    old_tag_ids = post_tags.pluck(:tag_id).map(&:to_i)
    add_tags(new_tag_ids - old_tag_ids)
    remove_tags(old_tag_ids - new_tag_ids)
  end

  def add_tags(ids)
    if !ids.empty?
      ids.each do |id|
        post_tag = post_tags.new(tag_id: id)
        post_tag.save
      end
    end
  end

  def remove_tags(ids)
    if !ids.empty?
      ids.each do |id|
        post_tag = post_tags.where(tag_id: id).first
        post_tag.destroy
      end
    end
  end

  # Returns a list of human-readable name-value pairs (or a separate name of
  # a value) to use as choices for a field.
  def choices(name, key = nil)
    items = {}
    items[:status] = {
      "Draft" => STATUS_DRAFT,
      "Published" => STATUS_PUBLISHED,
      "Archived" => STATUS_ARCHIVED,
    }

    return key ? items[name].key(key) : items[name]
  end
end

rubyonrailsapp/app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.page(params[:page])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/title/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to admin_posts_path, notice: "Post was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /posts/title
  def update
    if @post.update(post_params)
      redirect_to admin_posts_path, notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /posts/title
  def destroy
    @post.destroy
    redirect_to admin_posts_url, notice: "Post was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :body, :snippet, :status, :new_tag_ids => [])
  end
end

rubyonrailsapp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'application_blog'

  # GET /posts
  def index
    @posts = Post.published.page(params[:page])
  end

  # GET /posts/title
  def show
    @post = Post.friendly.find(params[:id])
  end

  # GET /posts/archive
  def archive
    posts = Post.active
    @years = {}
    posts.each do |post|
      year = post.published_date.strftime("%Y")
      @years[year] = @years.key?(year) ? @years[year].push(post) : [post]
    end
  end

  # GET /posts/tags/name
  def list_by_tag
    @posts = Post.active.includes(:tags).where(tags: { slug: params[:tag] }).page(params[:page])
    page_not_found if @posts.empty?
    @tag = Tag.find_by_slug(params[:tag])
  end
end

rubyonrailsapp/app/views/posts/archive.html.erb
<% content_for(:title) do %>
  Archive &middot;
<% end %>

<% content_for(:breadcrumbs) do %>
  <li><%= link_to "Blog", posts_path %></li>
  <li>Archive</li>
<% end %>

<div class="post-archive">
  <h1>Archive</h1>

  <% if @years.any? %>
    <% @years.each do |year, posts| %>
      <h3><%= year %></h3>

      <ul>
        <% posts.each do |post| %>
          <li>
            <div class="date">
              <%= post.published_date.strftime("%b %d") %>
            </div>

            <%= link_to post.title.html_safe, post_path(post) %>
          </li>
          <% end %>
      </ul>
    <% end %>
  <% else %>
    <p>No posts yet.</p>
  <% end %>
</div>

rubyonrailsapp/app/views/posts/index.html.erb
<% content_for(:breadcrumbs) do %>
  <li>Blog</li>
<% end %>

<% if @posts.any? %>
  <% @posts.each do |post| %>
    <div class="post">
      <h2><%= link_to post.title, post_path(post) %></h2>

      <div class="date">
        <span class="glyphicon glyphicon-time"></span>
        <%= post.published_date.strftime("%B %d, %Y") %>
      </div>

      <p><%= post.snippet.html_safe %></p>

      <%= link_to "Read more &rarr;".html_safe, post_path(post) %>
    </div>

    <%= paginate @posts %>
  <% end %>
<% else %>
  <h1>Blog</h1>

  <p>No posts yet.</p>
<% end %>

rubyonrailsapp/app/views/posts/list_by_tag.html.erb
<% content_for(:title) do %>
  <%= @tag.name %> &middot; Tags &middot;
<% end %>

<% content_for(:breadcrumbs) do %>
  <li><%= link_to "Blog", posts_path %></li>
  <li>Tags</li>
  <li><%= @tag.name %></li>
<% end %>

<% @posts.each do |post| %>
  <div class="post">
    <h2><%= link_to post.title, post_path(post) %></h2>

    <div class="date">
      <span class="glyphicon glyphicon-time"></span>
      <%= post.published_date.strftime("%B %d, %Y") %>
    </div>

    <p><%= post.snippet.html_safe %></p>

    <%= link_to "Read more &rarr;".html_safe, post_path(post) %>
  </div>

  <%= paginate @posts %>
<% end %>

rubyonrailsapp/app/views/posts/show.html.erb
<% content_for(:title) do %>
  <%= @post.title %> &middot;
<% end %>

<% content_for(:breadcrumbs) do %>
  <li><%= link_to "Blog", posts_path %></li>
  <li><%= @post.title %></li>
<% end %>

<div class="post">
  <h1><%= @post.title %></h1>

  <div class="date">
    <span class="glyphicon glyphicon-time"></span>
    <%= @post.published_date.strftime("%B %d, %Y") %>
  </div>

  <p><%= @post.body.html_safe %></p>

  <% if !@post.tags.blank? %>
    <div class="tags">
      <% @post.tags.each do |tag| %>
        <%= link_to tag.name, posts_by_tag_path(tag), :class => "btn btn-info btn-xs" %>
      <% end %>
    </div>
  <% end %>
</div>