rubyonrailsapp/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, skip: [:sessions, :passwords]
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'sign_in', to: 'users/sessions#create', as: :user_session
    match 'sign_out', to: 'users/sessions#destroy',
      via: Devise.mappings[:user].sign_out_via, as: :destroy_user_session

    get 'restore', to: 'users/passwords#new', as: :new_user_password
    get 'restore/confirm', to: 'users/passwords#edit', as: :edit_user_password
    resource 'restore', only: [:create, :update], controller: 'users/passwords', as: :user_password
  end

  namespace :admin do
    resources :users, :posts, :tags, :pages, except: :show

    root to: 'dashboard#index'
  end

  get 'blog/tags/:tag', to: 'posts#list_by_tag', as: :posts_by_tag
  resources :posts, only: [:index, :show], path: 'blog' do
    get 'archive', to: 'posts#archive', on: :collection
  end

  resource :feedback, only: [:new, :create], path_names: { new: '' }, path: 'feedback'
  get ':url', to: 'pages#show', url: /.+/, format: false, as: :page

  root to: 'site#index'
end

rubyonrailsapp/app/views/admin/pages/_form.html.erb
<%= form_with(model: page, url: form_url, local: true) do |form| %>
  <% if page.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:
      </div>

      <div class="panel-body">
        <ul>
          <% page.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :url, class: "control-label" %>
        <%= form.text_field :url, autofocus: true, class: "form-control" %>
        <p class="help-block">Example: "about/contact".</p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title, class: "control-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-9">
      <div class="form-group">
        <%= form.label :body, class: "control-label" %>
        <%= cktext_area :page, :body, ckeditor: { toolbar: "mini", height: 400 } %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= button_tag type: "submit", class: "btn btn-primary" do %>
      Save
    <% end %>
  </div>
<% end %>

rubyonrailsapp/app/views/admin/pages/_nav.html.erb
<ul class="nav nav-pills">
  <% if current_page?(admin_pages_path) %>
    <li class="active"><%= link_to "List", admin_pages_path %></li>
  <% else %>
    <li><%= link_to "<span class=\"glyphicon glyphicon-chevron-left\"></span> List".html_safe, admin_pages_path %></li>
  <% end %>

  <li class="<% if current_page?(new_admin_page_path) %>active<% end %>"><%= link_to "Add new", new_admin_page_path %></li>
</ul><br>

rubyonrailsapp/app/views/admin/pages/edit.html.erb
<% content_for(:title) do %>
  Edit page &middot;
<% end %>

<div class="page-header">
  <h1>Edit page</h1>
</div>

<%= render 'nav' %>
<%= render 'form', page: @page, form_url: admin_page_path(@page) %>

rubyonrailsapp/app/views/admin/pages/index.html.erb
<% content_for(:title) do %>
  Pages &middot;
<% end %>

<div class="page-header">
  <h1>Pages</h1>
</div>

<%= render 'nav' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>URL</th>
      <th>Title</th>
      <th>Created at</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% if @pages.empty? %>
      <tr>
        <td colspan="5">There are no records.</td>
      </tr>
    <% else %>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.id %></td>
          <td><%= page.url %></td>
          <td><%= link_to page.title, edit_admin_page_path(page.id) %></td>
          <td><%= l page.created_at, format: :long %></td>
          <td class="text-center">
            <%= link_to "<span class=\"glyphicon glyphicon-remove\"></span>".html_safe, admin_page_path(page),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate @pages %>

rubyonrailsapp/app/views/admin/pages/new.html.erb
<% content_for(:title) do %>
  Add new page &middot;
<% end %>

<div class="page-header">
  <h1>Add new page</h1>
</div>

<%= render 'nav' %>
<%= render 'form', page: @page, form_url: admin_pages_path %>